"""
Run Idea 3 as presented in the slides. You should run data_collection/nli_preprocess.py first. This program
expects to be run as `python3 idea3.py path_to_market_data.csv` where the CSV file is generated by
nli_preprocess.py.
"""

import pandas as pd
import sys

from algorithms.nlp_v5 import NomicHybridNLIPipeline
from algorithms.yes_conclusion_no_premise_arbitrage import find_arbitrage, build_arbitrage_structures
from transformers import AutoTokenizer, AutoModelForSequenceClassification


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: python3 idea3.py input.csv")
        sys.exit(1)

    df = pd.read_csv(sys.argv[1], low_memory=False)

    nli_model_name = "khalidalt/DeBERTa-v3-large-mnli"
    nli_tokenizer = AutoTokenizer.from_pretrained(nli_model_name)
    nli_model     = AutoModelForSequenceClassification.from_pretrained(nli_model_name)

    pipeline = NomicHybridNLIPipeline(
        embed_batch_size=256,
        k_neighbors=30,
        min_cluster_size=10,
        min_samples=5,
        nli_k_neighbors=3,
        nli_batch_size=32,
        entail_threshold=0.70,
        contradiction_threshold=0.45,
        fp16=True,
    )

    cluster_labels, implied_by, contradictions = pipeline.run(
        df,
        nli_model=nli_model,
        nli_tokenizer=nli_tokenizer,
    )

    arbitrage = find_arbitrage(*build_arbitrage_structures(df, implied_by, contradictions))


